var d=document.getElementsByClassName('swiper-wrapper');
var c=document.getElementsByClassName('swiper-container');
var at=document.getElementsByClassName('art_tag');
var ct=document.getElementsByClassName('controlli');
d[0].classList.remove('swiper-wrapper');
c[0].classList.remove('swiper-container');
var n=document.getElementsByClassName('new-comments');
var f=document.getElementsByTagName('footer');
n[0].setAttribute('style','position:absolute;left:-5000px');
f[0].setAttribute('style','position:absolute;left:-5000px');
f[1].setAttribute('style','position:absolute;left:-5000px');
at[0].setAttribute('style','position:absolute;left:-5000px');
ct[1].setAttribute('style','position:absolute;left:-5000px');
ct[0].setAttribute('style','position:absolute;left:-5000px');
